# Generated by Django 6.0.3 on 2026-04-03 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_author_remove_movie_genre_movie_author_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('full_name', 'date_of_birth')},
        ),
    ]
