# Generated by Django 6.0.3 on 2026-05-06 13:22

import movies.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_rating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=movies.utils.movie_image_upload_path),
        ),
    ]
